jobs:
- job_name: EQ
  version: 1
  flink_address: http://172.16.132.6:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-1
  sink_topic: T-N
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
