jobs:
- job_name: 9O
  version: 2
  flink_address: http://172.16.96.51:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-3
  sink_topic: T-9
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: KO
  version: 1
  flink_address: http://172.16.96.52:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-4
  sink_topic: T-N
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: 9G
  version: 1
  flink_address: http://172.16.96.52:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-8
  sink_topic: T-3
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: 9Q
  version: 1
  flink_address: http://172.16.132.8:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-9
  sink_topic: T-5
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: SI
  version: 1
  flink_address: http://172.16.132.9:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-10
  sink_topic: T-7
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: GU
  version: 2
  flink_address: http://172.16.177.7:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-2
  sink_topic: T-5
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: TA
  version: 1
  flink_address: http://172.16.177.7:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-6
  sink_topic: T-2
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: 3D
  version: 2
  flink_address: http://172.16.177.7:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-9
  sink_topic: T-3
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: A0
  version: 1
  flink_address: http://172.16.96.52:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-10
  sink_topic: T-2
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
- job_name: CG
  version: 2
  flink_address: http://172.16.177.7:8081
  mqtt_address: tcp://172.16.96.51:1883
  source_topic: T-N
  sink_topic: T-10
  entry_class: flinkpackage.FlowCheck
  jar_path: /usr/src/app/jars/flinktest-1.jar
